### ISSUE TITLE
Load of users with client-certificate and client-key paths

### ISSUE THREAD

**Issue by hirishh** [kubernetes-client/c#166]
Hello all,

I was playing with the official python and c library and there is a difference in how the kubeconfig is loaded.

For example if we have a kubeconfig like this: 
```
users:
- name: userA
  user:
    client-certificate-data: LS0tLS1C...S0tCg==
    client-key-data: LS0tLS1CRU...LQo=
- name: userB
  user:
    client-certificate: /path/to/client.crt
    client-key: /path/to/client.key
```

The python lib is able to load both users, instead the C lib is able to load only userA. I've checked the code and indeed the load of the second variant of the configuration is not implemented.

Is it a known limitation of the C lib?
