### ISSUE TITLE
v1_daemon_set_convertToJSON is returning NULL cJSON object

### ISSUE THREAD

**Issue by hirishh** [kubernetes-client/c#193]
Hello,

I've debugged this and this function is returning null while parsing the status. I have a simple Daemonset with this status:

```
status:
  currentNumberScheduled: 1
  numberMisscheduled: 0
  desiredNumberScheduled: 1
  numberReady: 1
  observedGeneration: 1
  updatedNumberScheduled: 1
  numberAvailable: 1
```

The conversion is failing here: https://github.com/kubernetes-client/c/blob/master/kubernetes/model/v1_daemon_set_status.c#L113

Is there any reason why this code must check the value of the int and fail if it's zero? I don't understand the logic here.

Best,

hirishh
