### ISSUE TITLE
Issues with minikube

### ISSUE THREAD

**Issue by swhoro** [kubernetes-client/c#197]
When I use this c lib on minikube,  `CoreV1API_listNamespacedEndpoints` (and some other apis) will print error:
```
curl_easy_perform() failed

URL: https://192.168.49.2:8443/api/v1/namespaces/default/endpoints?allowWatchBookmarks=0&limit=0&sendInitialEvents=0&timeoutSeconds=0&watch=0
IP: 192.168.49.2
PORT: 8443
SCHEME: HTTPS
StrERROR: SSL peer certificate or SSH remote key was not OK
The return code of HTTP request=0
Cannot get any service.
```

It seems when `load_kube_config`, the `apiKeys` cannot parse correctly (maybe it is because there is no api token in my `~/.kube/config` ?)

But the golang lib runs normally.

minikube version: 
```
minikube version: v1.30.1
commit: 08896fd1dc362c097c925146c4a0d0dac715ace0
```

kubectl version:
```yaml
clientVersion:
  buildDate: "2023-05-17T14:20:07Z"
  compiler: gc
  gitCommit: 7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647
  gitTreeState: clean
  gitVersion: v1.27.2
  goVersion: go1.20.4
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-03-15T13:33:12Z"
  compiler: gc
  gitCommit: 9e644106593f3f4aa98f8a84b23db5fa378900bd
  gitTreeState: clean
  gitVersion: v1.26.3
  goVersion: go1.19.7
  major: "1"
  minor: "26"
  platform: linux/amd64
```

**Comment by swhoro** [comment]
> What does your kube config file look like? It should be in `$HOME/.kube/config` Please paste it into this issue, but please make sure to redact any secret data (e.g. certificates) first.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/***/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sat, 15 Jul 2023 21:04:32 CST
        provider: minikube.sigs.k8s.io
        version: v1.30.1
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 15 Jul 2023 21:04:32 CST
        provider: minikube.sigs.k8s.io
        version: v1.30.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/***/.minikube/profiles/minikube/client.crt
    client-key: /home/***/.minikube/profiles/minikube/client.key
```
